require('dotenv').config();
require('./config/database');
var Question = require('./models/Question');

Question.remove({}).then(() => {
    Question.create([
      {question: 'What three words would passengers never want to hear a pilot say?'},
      {question: 'You would never go on a carnival ride called BLANK'},
      {question: 'The secret to a happy life...'},
      {question: 'Name a candle scent designed specifically for Nicki Minaj'},
      {question: 'You should never give alcohol to BLANK'},
      {question: 'Everyone knows that monkeys hate BLANK'},
      {question: 'The worst thing about living in Hell'},
      {question: 'The worst thing for an evil witch to turn you into'},
      {question: 'The best pet ever would be...'},
      {question: 'Something squirrels probably do when no one is looking?'},
      {question: 'What is the Mona Lisa smiling about?'},
      {question: 'The Skittles flavor that just missed the cut'},
      {question: 'The crime you would commit if you could get away with it'},
      {question: 'Come up with a title for an adult version of any classic video game'},
      {question: 'The real reason the dinosaurs died'},
      {question: 'The best way to keep warm on a cold winter night'},
      {question: 'The college major you would like to major in'},
      {question: 'The new national anthem for the USA should be...'},
      {question: 'The name of a pizza place you should never order from'},
      {question: 'The worst way to be murdered'},
      {question: 'A not-very-scary name for a pirate'},
      {question: 'A dangerous thing to do while driving'},
      {question: 'The real reason why penguins cannot fly'},
      {question: 'The hardest thing about being Batman'},
      {question: 'Why does the Tower of Pisa lean?'},
      {question: 'What is wrong with kids these days?'},
      {question: 'Something you should never use as a scarf'},
      {question: 'Invent a holiday that you think everyone would enjoy'},
      {question: 'The worst thing you could stuff a bed mattress with'},
      {question: 'Where do babies come from?'},
      {question: 'Something you would like to fill a swimming pool with'},
      {question: 'The best pick-up line for an elderly singles mixer'},
      {question: 'The most difficult yoga pose known to mankind is'},
      {question: 'A vanity license for an expensive car would say...'},
      {question: 'A terrible name for a clown'},
      {question: 'An alternate use for a banana'},
      {question: 'Something you should never say to your mother'},
      {question: 'How many monkeys is too many monkeys?'},
      {question: 'Come up with a catchier, name for the Bible'},
      {question: 'The three ingredients in the worst smoothie ever'},
      {question: 'The most presidential name you can think of'},
      {question: 'A good way to get fired'},
      {question: 'A good place to hide boogers'},
      {question: 'What is beef really made of?'},
      {question: 'The grossest thing you would put in your mouth for $20'},
      {question: 'The name of a new perfume by Betty White'},
      {question: 'One thing never to do on a first date'},
      {question: 'The worst name for a robot'},
      {question: 'Who let the dogs out?'},
      {question: 'The newly discovered ice cream flavor'},
      {question: 'What do vegans taste like?'},
      {question: 'Name the title for new movie starring a talking goat'},
      {question: 'Something that would not work well as a dip for tortilla chips'},
      {question: 'A terrible theme for a high school prom'},
      {question: 'Something you should not whisper to your grandmother'},
      {question: 'The worst family secret that could come out over Thanksgiving dinner'},
      {question: 'A lawn decoration sure to upset the neighbors'},
      {question: 'Fun thing to do if locked in the mall overnight'},
      {question: 'Pants would be a whole lot better if they were BLANK'},
      {question: 'The most awesome Guinness World Record to break'},
      {question: 'Something that would not work as well as skis'},
      {question: 'What would someone say to get out of jury duty'},
      {question: 'The only time that murder is acceptable'},
      {question: 'A good sign that your house is haunted'},
      {question: 'A bad occupation for a robot to have'},
      {question: 'What time is it?'},
      {question: 'A short motto everyone should live by'},
      {question: 'A short motto everyone should live by'},
      {question: 'The best way to start your day'},
      {question: 'Something that is currently legal that should be banned'},
      {question: 'Something you should not buy off of Craigslist'},
      {question: 'A great name to have on a fake I.D.'},
      {question: 'What really happened to Amelia Earhart'},
      {question: 'If at first you dont succeed...'},
      {question: 'A fun trick to play on your doctor'},
      {question: 'The next product for Matthew McConaughey to endorse'},
      {question: 'How would you escape from prison'},
      {question: 'A gift nobody would want'},
      {question: 'Where do missing socks go'},
      {question: 'The first sign you are getting old'},
      {question: 'A rejected crayon color'},
      {question: 'Bad advice for new graduates'},
      {question: 'A product you would leave a bad review for'},
      {question: 'A terrible talent to have'},
      {question: 'Scientists Are Shocked to Discover BLANK'},
      {question: 'What happens when pigs fly'},
      {question: 'The worst shape for an animal cracker'},
      {question: 'The real secret to living to age 100'},
      {question: 'Another use for cooked spaghetti'},
      {question: 'A weird way to greet someone'},
      {question: 'Why so serious?'},
      {question: 'The best thing about being really dumb'},
      {question: 'You know you are really drunk when...'},
      {question: 'Another use for grape soda'},
      {question: 'The worst name for a rap artist'},
      {question: 'What Chewbacca has really been saying all these years'},
      {question: 'What you want your gravestone to read'},
      {question: 'Life is more fun with BLANK'},
      {question: 'What is black and white and red all over?'},
      {question: 'America is still number one in...'},
      {question: 'What you call a baby sasquatch'},
      {question: 'The worst thing about Canada'},
      {question: 'A strange thing to keep as a pet'},
      {question: 'The sound a tree actually makes when it falls and no one is around to hear it'},
      {question: 'A good use for toenail clippings'},
      {question: 'Trash talk you would hear at a chess meet'},
      {question: 'What were the apostles talking about at the Last Supper?'},
      {question: 'The worst way to fly'},
      {question: 'Lower your heating bills by...'},
      {question: 'What to do when your parachute fails'},
      {question: 'Sleepwalking is not as bad as BLANK'},
      {question: 'The name of a font nobody would ever use'},
      {question: 'Life would be so much better if we all lived in BLANK'},
      {question: 'Something you would love to smash with a wrecking ball'},
      {question: 'A substitute for salad dressing'}
      
    ]).then(() => {
      process.exit();
    });
  })
